/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.bpm.deep;import cn.zhuatech.bpm.common.ApiResponse;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/workflow-ops") public class DeepWorkflowController{private final DeepWorkflowService s;/**
                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                              */
public DeepWorkflowController(DeepWorkflowService x){s=x;}/**
                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                        */
@GetMapping("/workspace")ApiResponse<?> workspace(){return ApiResponse.ok(s.workspace());}/**
                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                  */
@PostMapping("/instances")ApiResponse<?> start(@RequestBody DeepWorkflowService.StartInput x){return ApiResponse.ok(s.start(x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                   */
@PostMapping("/tasks/{id}/claim")ApiResponse<?> claim(@PathVariable Long id,@RequestBody DeepWorkflowService.ClaimInput x){return ApiResponse.ok(s.claim(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/tasks/{id}/delegate")ApiResponse<?> delegate(@PathVariable Long id,@RequestBody DeepWorkflowService.ClaimInput x){return ApiResponse.ok(s.delegate(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@PostMapping("/tasks/{id}/decision")ApiResponse<?> decide(@PathVariable Long id,@RequestBody DeepWorkflowService.DecisionInput x){return ApiResponse.ok(s.decide(id,x));}}
