/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.bpm.deep;import cn.zhuatech.bpm.common.ApiResponse;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/admin/workflow-ops") @PreAuthorize("hasRole('ADMIN')") public class DeepWorkflowAdminController{private final DeepWorkflowService s;/**
                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                           */
public DeepWorkflowAdminController(DeepWorkflowService x){s=x;}/**
                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                          */
@PostMapping("/definitions")ApiResponse<?> create(@RequestBody DeepWorkflowService.DefinitionInput x){return ApiResponse.ok(s.create(x));}/**
                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/definitions/{id}/nodes")ApiResponse<?> node(@PathVariable Long id,@RequestBody DeepWorkflowService.NodeInput x){return ApiResponse.ok(s.addNode(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@PostMapping("/definitions/{id}/publish")ApiResponse<?> publish(@PathVariable Long id){return ApiResponse.ok(s.publish(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
@PostMapping("/sla/escalate")ApiResponse<?> escalate(@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) LocalDateTime asOf){return ApiResponse.ok(s.escalate(asOf));}}
